// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (guid, created_at) VALUES ($1, now()) ON CONFLICT (guid) DO NOTHING
`

func (q *Queries) InsertUser(ctx context.Context, guid uuid.UUID) error {
	_, err := q.exec(ctx, q.insertUserStmt, insertUser, guid)
	return err
}
