// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusbill/internal/models"
)

// PostUserBalanceReduceOKCode is the HTTP code returned for type PostUserBalanceReduceOK
const PostUserBalanceReduceOKCode int = 200

/*
PostUserBalanceReduceOK Успешное выполнение операции

swagger:response postUserBalanceReduceOK
*/
type PostUserBalanceReduceOK struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostUserBalanceReduceOK creates PostUserBalanceReduceOK with default headers values
func NewPostUserBalanceReduceOK() *PostUserBalanceReduceOK {

	return &PostUserBalanceReduceOK{}
}

// WithPayload adds the payload to the post user balance reduce o k response
func (o *PostUserBalanceReduceOK) WithPayload(payload *models.DefaultStatusResponse) *PostUserBalanceReduceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user balance reduce o k response
func (o *PostUserBalanceReduceOK) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserBalanceReduceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUserBalanceReduceForbiddenCode is the HTTP code returned for type PostUserBalanceReduceForbidden
const PostUserBalanceReduceForbiddenCode int = 403

/*
PostUserBalanceReduceForbidden Клиентская ошибка

swagger:response postUserBalanceReduceForbidden
*/
type PostUserBalanceReduceForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostUserBalanceReduceForbidden creates PostUserBalanceReduceForbidden with default headers values
func NewPostUserBalanceReduceForbidden() *PostUserBalanceReduceForbidden {

	return &PostUserBalanceReduceForbidden{}
}

// WithPayload adds the payload to the post user balance reduce forbidden response
func (o *PostUserBalanceReduceForbidden) WithPayload(payload *models.DefaultStatusResponse) *PostUserBalanceReduceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user balance reduce forbidden response
func (o *PostUserBalanceReduceForbidden) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserBalanceReduceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUserBalanceReduceInternalServerErrorCode is the HTTP code returned for type PostUserBalanceReduceInternalServerError
const PostUserBalanceReduceInternalServerErrorCode int = 500

/*
PostUserBalanceReduceInternalServerError Серверная ошибка

swagger:response postUserBalanceReduceInternalServerError
*/
type PostUserBalanceReduceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostUserBalanceReduceInternalServerError creates PostUserBalanceReduceInternalServerError with default headers values
func NewPostUserBalanceReduceInternalServerError() *PostUserBalanceReduceInternalServerError {

	return &PostUserBalanceReduceInternalServerError{}
}

// WithPayload adds the payload to the post user balance reduce internal server error response
func (o *PostUserBalanceReduceInternalServerError) WithPayload(payload *models.DefaultStatusResponse) *PostUserBalanceReduceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user balance reduce internal server error response
func (o *PostUserBalanceReduceInternalServerError) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserBalanceReduceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
