// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"otusbill/internal/models"
)

// PostUserBalanceIncreaseOKCode is the HTTP code returned for type PostUserBalanceIncreaseOK
const PostUserBalanceIncreaseOKCode int = 200

/*
PostUserBalanceIncreaseOK Успешное создание пользователя

swagger:response postUserBalanceIncreaseOK
*/
type PostUserBalanceIncreaseOK struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostUserBalanceIncreaseOK creates PostUserBalanceIncreaseOK with default headers values
func NewPostUserBalanceIncreaseOK() *PostUserBalanceIncreaseOK {

	return &PostUserBalanceIncreaseOK{}
}

// WithPayload adds the payload to the post user balance increase o k response
func (o *PostUserBalanceIncreaseOK) WithPayload(payload *models.DefaultStatusResponse) *PostUserBalanceIncreaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user balance increase o k response
func (o *PostUserBalanceIncreaseOK) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserBalanceIncreaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUserBalanceIncreaseInternalServerErrorCode is the HTTP code returned for type PostUserBalanceIncreaseInternalServerError
const PostUserBalanceIncreaseInternalServerErrorCode int = 500

/*
PostUserBalanceIncreaseInternalServerError Серверная ошибка

swagger:response postUserBalanceIncreaseInternalServerError
*/
type PostUserBalanceIncreaseInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.DefaultStatusResponse `json:"body,omitempty"`
}

// NewPostUserBalanceIncreaseInternalServerError creates PostUserBalanceIncreaseInternalServerError with default headers values
func NewPostUserBalanceIncreaseInternalServerError() *PostUserBalanceIncreaseInternalServerError {

	return &PostUserBalanceIncreaseInternalServerError{}
}

// WithPayload adds the payload to the post user balance increase internal server error response
func (o *PostUserBalanceIncreaseInternalServerError) WithPayload(payload *models.DefaultStatusResponse) *PostUserBalanceIncreaseInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user balance increase internal server error response
func (o *PostUserBalanceIncreaseInternalServerError) SetPayload(payload *models.DefaultStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserBalanceIncreaseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
