// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserCreateParams Параметры создания пользователя
//
// swagger:model UserCreateParams
type UserCreateParams struct {

	// Имя пользователя
	// Example: Дроздобород Эдуард
	// Required: true
	// Format: uuid
	GUID strfmt.UUID `json:"guid"`
}

// Validate validates this user create params
func (m *UserCreateParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserCreateParams) validateGUID(formats strfmt.Registry) error {

	if err := validate.Required("guid", "body", strfmt.UUID(m.GUID)); err != nil {
		return err
	}

	if err := validate.FormatOf("guid", "body", "uuid", m.GUID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user create params based on context it is used
func (m *UserCreateParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserCreateParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserCreateParams) UnmarshalBinary(b []byte) error {
	var res UserCreateParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
