// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserBalance Текущий баланс пользователя
//
// swagger:model UserBalance
type UserBalance struct {

	// amount
	Amount float64 `json:"amount"`

	// guid
	// Format: uuid
	GUID strfmt.UUID `json:"guid"`
}

// Validate validates this user balance
func (m *UserBalance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserBalance) validateGUID(formats strfmt.Registry) error {
	if swag.IsZero(m.GUID) { // not required
		return nil
	}

	if err := validate.FormatOf("guid", "body", "uuid", m.GUID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user balance based on context it is used
func (m *UserBalance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserBalance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserBalance) UnmarshalBinary(b []byte) error {
	var res UserBalance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
