billDp:
  billApp:
    image:
      repository: nikolaygr/otusbill
      tag: v0.1
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
billServiceLb:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
confMap:
  postgresDbName: postgres  
  postgresPort: "5432"
  postgresUser: postgres
kubernetesClusterDomain: cluster.local
migratePostgres:
  backoffLimit: 4
  migratePostgres:
    image:
      repository: nikolaygr/otusbill
      tag: v0.1
